### ISSUE TITLE
List of Bugs

### ISSUE THREAD

**Issue by InnLumin** [LadyCelastia/HitboxRemaster#2]
These are a list of problem/bugs I have encountered.

1. backstab() and hitboxbackstab() doesn't work. I tested it with a basic fireball and a sword and it just comes up false every time. this was after fixing the error it had of comparing a cframe to a number.
2. Types are broken. Mainly any colon functions like activate and deactivate.
3. I don't understand the reason for passing the humanoid and hit part, they are in the same area. Same thing for the data bundle, I don't see the point of it besides for backstab which couldn't it just get that data from self? Realistically should just pass hit part.
4. The hitbox would randomly not work (this could very likely be my own code as the test fireball would work with no problems but for some reason the sword doesn't)
5. Using the sphere shape completely stops it from finding any hits.
6. newHitbox() doesn't have a type of the table so it can autocomplete, either add the type or completely remove the table and keep "Hitbox.CopyCFrame = Part"

**Comment by LadyCelastia** [comment]
Will look into backstab and typing issues.

Can you send me the code of your melee weapon? I tested the module with melee weapons the most and it worked perfectly fine with both box and sphere shapes. It might be an edge case with how you utilize the hitbox. Thanks.

Passing Humanoid and HitPart is intentional, as hitbox is only meant to detect hits on humanoids. A HitPart would allow for easy detection of headshots and such, and a Humanoid would reduce boilerplate code for finding the hit character's humanoid. Though now that I think about it, there can indeed be uses for a hitbox that can detect hits on non-humanoid parts. I'll add that in within a few days. As for HitboxDataBundle, it is a snapshot of the hitbox's basic data at the time of hit registration. Meaning it does not change even if it's passed to a backstab checking method one second later. This enables asynchronous backstab checking operations.

**Comment by InnLumin** [comment]
I tested the updated module and notice the same thing, sometimes it detects no hits and other times it does. The hitbox.hit function does still fire when hitting the own character but it doesnt detect any other character. Another thing I noticed was the "CopyCFrame" doesn't copy the size of the part given.

I got no errors either, I changed up a bit of the code but it is mainly the same. I'll post the file once again.

After testing it some more I have realized the Pierce by default is set to 1 and since the hitbox is always hitting myself it will automatically put a debounce on myself and stop it from hitting any other humanoid. I'd imagine you would need to check if the hitbox hits myself. Once I put the pierce to 2 it worked fine with no problems.

Thank you for explaining the reasoning behind the passing of the values given.

The sphere shape stopped working for my fireball and sword.

[HitboxRemasterError.zip](https://github.com/LadyCelastia/HitboxRemaster/files/12853847/HitboxRemasterError.zip)

**Comment by LadyCelastia** [comment]
For the sword, I think I see what's wrong.
The default pierce of every hitbox is 1, meaning it can only detect hit on 1 humanoid. By default, the IgnoreList of every hitbox is nil, meaning the hitbox can detect the user's own character and use up the pierce, resulting in no further hit detection. That's why Hitbox:AddIgnore(BasePart or Model) exists, which will make the hitbox completely ignore any part or model added into the ignore list and not use up a pierce.

As for the typechecking, the way I'm doing it doesn't work with methods. I'll have to completely overhaul it, which may take up to a week. I'll release the type overhaul with the detecting non-humanoid together.

Both IsHitboxBackstab and IsBackstab are now fixed! Note: IsHitboxBackstab originates from the hitbox's position at time of hitting, while IsBackstab originates from the given character's root position. It is recommended to use IsBackstab over IsHitboxBackstab if the hitbox is being used on a tool wielded by a character for higher accuracy.

Both IsHitboxBackstab and IsBackstab received a new OPTIONAL argument: Margin (HitPart, DataBundle, Margin) and (HitPart, Character, Margin) respectively.
Margin is a number that ranges from 0 to 0.5 (defaults to 0.32), which determines how leniant the backstab detection is. 0.5 would allow for side-stabs counting as backstabs, while 0.1 requires the originating position to be almost perfectly aligned for a backstab. Basically, higher = easier backstab, lower = harder backstab.

Currently planned updates: Type overhaul, hitbox detection on non-humanoid parts, size compensation for hitbox

**Comment by InnLumin** [comment]
Yeah the Hitbox:AddIgnore() did fix it, I should of had noticed it. It would be worth adding it to the example code.

One thing I think would be worth doing is moving IsHitboxBackstab() and IsBackstab() to be apart of the main module as if you make a hitbox on the client, there is no way to check for the backstab on the server and if you do it on the client they could spoof this value and make every hit a backstab.

**Comment by LadyCelastia** [comment]
Added to example.
